#!/bin/bash

set -x
set -e

mkdir -p out
cd out

jarball1=canarymod.jar
if [ ! -f $jarball1 ] ; then
  wget -cq http://canarymod.net/releases/latest-download -O $jarball1
fi

jarball2=scriptcraft.jar
if [ ! -f out/$jarball2 ] ; then
  wget -cq http://scriptcraftjs.org/download/latest/scriptcraft-3.1.2/$jarball2 -O $jarball2
fi

wconf=world.cfg
cp ../src/world.cfg $wconf
sed -i '/^world-type=/          s/=.*$/=FLAT/'  $wconf
sed -i '/^generate-structures=/ s/=.*$/=false/' $wconf
sed -i '/^spawn-.*=/            s/=.*$/=false/' $wconf
sed -i '/^game-mode=/           s/=.*$/=2/'     $wconf

cd ..
docker build  --rm=true -t scriptcraft .

